# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "be263a0598e83dd1707646a23f8a42ec"
name = "pincode-shipping-rates"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products,write_shipping"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
automatically_update_urls_on_dev = true

url = "https://divided-early-limiting-battle.trycloudflare.com"
subpath = "pincode"
prefix = "apps"